### ISSUE TITLE
write1 seems to give wrong shape info

### ISSUE THREAD

**Issue by nilsbecker** [LaurentMazare/npy-ocaml#4]
i just wrote a fortran-ordered bigarray using write1. the file starts with 
```
NUMPY�F�{'descr': '<f8', 'fortran_order': True, 'shape': (184), } 
```
note that the shape is not a python tuple (this would have to be (184,)).
numpy refuses to load it, probably for this reason. indeed after i edit the file manually i can import it.

(maybe add a test case for write/read in all dimensions?)

**Comment by nilsbecker** [comment]
actually the file still seems to be broken: after editing the shape, the file is loaded but contains garbled values ?!

**Comment by nilsbecker** [comment]
the same happens if i first convert the array to a c-layout Bigarray.Array1.t

**Comment by nilsbecker** [comment]
os x, python 2.7.11, numpy 1.11.2

**Comment by nilsbecker** [comment]
if i wrap the vector in an extra dimension and write it with write2, the import in numpy works as expected. conclusion: write1 is broken, write2 ok.

**Comment by LaurentMazare** [comment]
Could you attach the problematic npy file ? Also are you using the current github tip or the opam package ?

**Comment by nilsbecker** [comment]
i was using the opam package. the file generated with write1 is here:
[tvals.npy.zip](https://github.com/LaurentMazare/npy-ocaml/files/1249327/tvals.npy.zip)

**Comment by nilsbecker** [comment]
the input bigarrays were actually vectors from lacaml - but that should not matter i think..

**Comment by LaurentMazare** [comment]
I just tweaked the github tip to fix this and added some tests for the single dimension case, would you mind giving it a try ?

**Comment by nilsbecker** [comment]
it's looking good now! i opam pinned and redid my example, and the shape is now reported as (184,) in the file. numpy successfully loads it. thanks!

**Comment by LaurentMazare** [comment]
Perfect, thanks for reporting the issue!
